# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_notificacao_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-id']},
        ),
    ]
