# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
        ('perfis', '0004_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='notificacoes',
            field=models.ManyToManyField(related_name='notificacao', to='notificacao.Notificacao'),
        ),
    ]
