# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20171128_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='notificacoes',
        ),
    ]
