# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_remove_perfil_notificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='fotos/none.jpg', upload_to='fotos/'),
        ),
    ]
