# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='img/photo.jpg', upload_to='img/'),
        ),
    ]
